/*--------------------------ОЧИЩЕНИЕ БАЗЫ---------------------------------*/
DROP TABLE IF EXISTS `ERROR_HISTORY`;
DROP TABLE IF EXISTS `ERRORS`;
DROP TABLE IF EXISTS `STATUSES`;
DROP TABLE IF EXISTS `URGENCY`;
DROP TABLE IF EXISTS `CRITICALNESS`;
DROP TABLE IF EXISTS `USERS`;
/*--------------------------ОЧИЩЕНИЕ БАЗЫ---------------------------------*/

CREATE TABLE IF NOT EXISTS `STATUSES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) COLLATE utf8_general_ci NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO STATUSES (ID, NAME) VALUES (1, 'New');
INSERT INTO STATUSES (ID, NAME) VALUES (2, 'Open');
INSERT INTO STATUSES (ID, NAME) VALUES (3, 'Solved');
INSERT INTO STATUSES (ID, NAME) VALUES (4, 'Closed');

CREATE TABLE IF NOT EXISTS `URGENCY` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) COLLATE utf8_general_ci NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO URGENCY (ID, NAME) VALUES (1, 'Very urgent');
INSERT INTO URGENCY (ID, NAME) VALUES (2, 'Urgent');
INSERT INTO URGENCY (ID, NAME) VALUES (3, 'Not urgent');
INSERT INTO URGENCY (ID, NAME) VALUES (4, 'Totally not urgent');

CREATE TABLE IF NOT EXISTS `CRITICALNESS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) COLLATE utf8_general_ci NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO CRITICALNESS (ID, NAME) VALUES (1, 'Сatastrophe!');
INSERT INTO CRITICALNESS (ID, NAME) VALUES (2, 'Critical');
INSERT INTO CRITICALNESS (ID, NAME) VALUES (3, 'Not critical');
INSERT INTO CRITICALNESS (ID, NAME) VALUES (4, 'Change request');

CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `NAME` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `SURNAME` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `USER_PASS` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE (`LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ERRORS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SHORT_DESCRIPTION` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `STATUS_ID` INT(10) UNSIGNED DEFAULT 1,
  `CRITICALNESS_ID` INT(10) UNSIGNED DEFAULT 1,
  `URGENCY_ID` INT(10) UNSIGNED DEFAULT 1,
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `STATUS_ID_I` (`STATUS_ID`),
  INDEX `URGENCY_ID_I` (`URGENCY_ID`),
  INDEX `CRITICALNESS_ID_I` (`CRITICALNESS_ID`),
  INDEX `USER_ID_I` (`USER_ID`),
  CONSTRAINT `ERRORS_STATUSES_FK` FOREIGN KEY (`STATUS_ID`) REFERENCES `STATUSES` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ERRORS_CRITICALNESS_FK` FOREIGN KEY (`CRITICALNESS_ID`) REFERENCES `CRITICALNESS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ERRORS_URGENCY_FK` FOREIGN KEY (`URGENCY_ID`) REFERENCES `URGENCY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ERRORS_USERS_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ERROR_HISTORY` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `STATUS_ID`  INT(10) UNSIGNED NOT NULL,
  `ERROR_ID`  INT(10) UNSIGNED NOT NULL,
  `USER_ID`  INT(10) UNSIGNED NOT NULL,
  `COMMENT` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `STATUS_ID_I` (`STATUS_ID`),
  INDEX `ERROR_ID_I` (`ERROR_ID`),
  INDEX `USER_ID_I` (`USER_ID`),
  CONSTRAINT `ERROR_HISTORY_STATUSES_FK` FOREIGN KEY (`STATUS_ID`) REFERENCES `STATUSES` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ERROR_HISTORY_ERRORS_FK` FOREIGN KEY (`ERROR_ID`) REFERENCES `ERRORS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ERROR_HISTORY_USERS_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;